name: build
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: "Environment"
        options:
          - test



jobs:
  build:
    name: "Deployment"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Code"
        uses: "actions/checkout@v3"

      - name: "Login to GitHub Container Registry"
        uses: "docker/login-action@v1"
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.SECRET_TOKEN }}

      - name: Build Docker Image
        run: |
          docker-compose up --build -d